# This workflow will build mirrorSpeedTest and test the cmd mode
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Build
      run: go build -o mirrorSpeedTest main/main.go

    - name: Test cmd mode for US
      run: ./mirrorSpeedTest -c US

    - name: Test cmd mode for CA
      run: ./mirrorSpeedTest -c CA

    - name: Test cmd mode for AU
      run: ./mirrorSpeedTest -c AU

    - name: Test cmd mode for BR
      run: ./mirrorSpeedTest -c BR

    - name: Test cmd mode for CA
      run: ./mirrorSpeedTest -c CA

    - name: Test cmd mode for CN
      run: ./mirrorSpeedTest -c CN

    - name: Test cmd mode for FR
      run: ./mirrorSpeedTest -c FR

    - name: Test cmd mode for DE
      run: ./mirrorSpeedTest -c DE